# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
       #FOS\UserBundle\Model\UserInterface: bcrypt
       FOS\UserBundle\Model\UserInterface: 
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
        #AppBundle\Entity\Usuario:
        #    algorithm: sha512
        #    encode-as-base64: true
        #    iterations: 10
    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_INVENTARIO, ROLE_FACTURACION, ROLE_INFORMES]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        #user_db:
        #    entity: {class: AppBundle\Entity\Usuario, property: username}
        #in_memory:
        #    memory:
         #       users:
         #           user:  { password: userpass, roles: [ 'ROLE_USER' ] }
          #          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # the login page has to be accessible for everybody
        login:
            pattern:  ^/(login$|register)
            anonymous: true
        resetting:
            pattern:  ^/resetting/(request|send-email|check-email|reset|reset/$)
            anonymous: true
        order_add:
            pattern:  ^/order/add
            anonymous: true    

        # secures part of the application
        
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        secured_area:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                 path:   fos_user_security_logout
                 target: fos_user_security_login
            anonymous:   false

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
    access_decision_manager:
        strategy: unanimous        
    access_control:
        #- { path: ^/arxis/user, roles: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/order/add, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/arxis/user, roles: ROLE_ADMIN }
        - { path: ^/arxis/role, roles: ROLE_ADMIN }
        - { path: ^/proovedores, roles: ROLE_ADMIN }
        
        