order_index:
    path:     /
    defaults: { _controller: "AppBundle:Order:index" }
    methods:  GET

order_results:
    path:     /results
    defaults: { _controller: "AppBundle:Order:indexResults" }
    methods:  GET    

order_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Order:show" }
    methods:  GET

order_new:
    path:     /new
    defaults: { _controller: "AppBundle:Order:new" }
    methods:  [GET, POST]

order_add:
    path:     /add
    defaults: { _controller: "AppBundle:Order:add" }
    methods:  [GET, POST]

order_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Order:edit" }
    methods:  [GET, POST]

order_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Order:delete" }
    methods:  DELETE
